"""CLI entry point for the KRR Fact Verification System.

Usage examples:
    python main.py --pipeline krr
    python main.py --pipeline baseline --env-file .env.prod
    python main.py --pipeline both --output-json results.json
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    stream=sys.stderr,
)
logger = logging.getLogger(__name__)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        prog="main.py",
        description="KRR Fact Verification System — run KRR and/or Baseline RAG pipelines.",
    )
    parser.add_argument(
        "--pipeline",
        choices=["krr", "baseline", "both"],
        default="both",
        help="Which pipeline(s) to run (default: both).",
    )
    parser.add_argument(
        "--env-file",
        default=".env",
        metavar="PATH",
        help="Path to the .env configuration file (default: .env).",
    )
    parser.add_argument(
        "--output-json",
        default=None,
        metavar="PATH",
        help=(
            "Override JSON_OUTPUT_PATH from config: write per-claim KRR results "
            "to this file (newline-delimited JSON)."
        ),
    )
    parser.add_argument(
        "--claim",
        default=None,
        metavar="TEXT",
        help=(
            "Demo mode: verify a single claim and print both KRR and Baseline "
            "verdicts with explanation. Skips dataset loading and evaluation."
        ),
    )
    return parser.parse_args(argv)


def _build_llm_backend(config):
    """Instantiate the configured LLM backend.

    Args:
        config: A :class:`~config.Config` instance.

    Returns:
        An :class:`~baseline.llm.LLMBackend` implementation.
    """
    from baseline.llm import HuggingFaceLLM, KeywordLLM, OpenAILLM

    if config.llm_backend == "openai":
        logger.info("Initializing OpenAI LLM backend (model=%s).", config.openai_model)
        return OpenAILLM(config)
    elif config.llm_backend == "keyword":
        logger.info("Initializing KeywordLLM backend (no model download required).")
        return KeywordLLM()
    else:
        logger.info(
            "Initializing HuggingFace LLM backend (model=%s).", config.hf_model_name
        )
        return HuggingFaceLLM(config)


def _write_error_analysis(
    records,
    krr_results,
    baseline_results,
    output_dir: Path,
) -> None:
    """Write output/error_analysis.md with per-claim failure breakdown."""
    from models import FeverRecord, KRRResult, BaselineResult

    lines = [
        "# Error Analysis Report",
        "",
        "Auto-generated by `main.py`. Shows every incorrect KRR prediction with root-cause analysis.",
        "",
    ]

    error_counts = {
        "extraction_failure": 0,
        "retrieval_error": 0,
        "reasoning_mismatch": 0,
        "negation_comparative": 0,
        "correct": 0,
    }

    n = len(records)
    for i in range(n):
        record: FeverRecord = records[i]
        krr: KRRResult | None = krr_results[i] if krr_results else None
        bl: BaselineResult | None = baseline_results[i] if baseline_results else None

        krr_verdict = krr.verdict if krr else "N/A"
        bl_verdict = bl.verdict if bl else "N/A"
        gt = record.label
        correct = krr_verdict == gt

        if correct:
            error_counts["correct"] += 1
            continue

        # Determine failure reason
        if krr and not krr.claim_triples:
            reason = "**Extraction failure** — no triples extracted from claim"
            error_counts["extraction_failure"] += 1
        elif krr and krr.support_count == 0 and krr.refute_count == 0:
            reason = "**Retrieval/reasoning** — retrieved evidence produced no matching triples"
            error_counts["retrieval_error"] += 1
        elif krr and krr.verdict == "SUPPORTS" and gt == "REFUTES":
            reason = "**Reasoning mismatch** — false support (synonym or substring match)"
            error_counts["reasoning_mismatch"] += 1
        elif krr and krr.verdict == "REFUTES" and gt == "SUPPORTS":
            reason = "**Reasoning mismatch** — false refute (synonym treated as different value)"
            error_counts["reasoning_mismatch"] += 1
        else:
            reason = "**Semantic/structural limit** — negation, comparative, or coreference"
            error_counts["negation_comparative"] += 1

        lines.append(f"## Claim {i + 1}: {record.claim}")
        lines.append("")
        lines.append(f"| Field | Value |")
        lines.append(f"|-------|-------|")
        lines.append(f"| Ground Truth | `{gt}` |")
        lines.append(f"| KRR Prediction | `{krr_verdict}` |")
        lines.append(f"| Baseline Prediction | `{bl_verdict}` |")
        lines.append(f"| Failure Reason | {reason} |")
        lines.append("")

        if krr:
            lines.append("**Retrieved Evidence:**")
            for ev in krr.retrieved_evidence:
                lines.append(f"- {ev}")
            lines.append("")
            lines.append("**Claim Triples:**")
            if krr.claim_triples:
                for t in krr.claim_triples:
                    lines.append(f"- `{t.to_canonical_string()}`")
            else:
                lines.append("- *(none extracted)*")
            lines.append("")
            lines.append("**Evidence Triples:**")
            if krr.evidence_triples:
                for t in krr.evidence_triples:
                    lines.append(f"- `{t.to_canonical_string()}`")
            else:
                lines.append("- *(none extracted)*")
            lines.append("")
            lines.append(
                f"Support: {krr.support_count} | Refute: {krr.refute_count} | "
                f"Irrelevant: {krr.irrelevant_count}"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    # Summary
    total_errors = n - error_counts["correct"]
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total claims:** {n}")
    lines.append(f"- **Correct (KRR):** {error_counts['correct']} ({error_counts['correct']/n:.0%})")
    lines.append(f"- **Total errors:** {total_errors}")
    lines.append("")
    lines.append("### Error breakdown by component:")
    lines.append("")
    lines.append(f"| Root Cause | Count | % of Errors |")
    lines.append(f"|------------|-------|-------------|")
    for key, label in [
        ("extraction_failure", "Extraction failure (no triples)"),
        ("retrieval_error", "Retrieval / no matching triples"),
        ("reasoning_mismatch", "Reasoning mismatch (synonym/paraphrase)"),
        ("negation_comparative", "Structural limit (negation/comparative)"),
    ]:
        count = error_counts[key]
        pct = f"{count/total_errors:.0%}" if total_errors > 0 else "0%"
        lines.append(f"| {label} | {count} | {pct} |")
    lines.append("")
    lines.append("### What improved after fixes:")
    lines.append("- Passive voice inversion: `shakespeare|write|hamlet` now extracted")
    lines.append("- Negation detection: `not visible from space` preserved in triple")
    lines.append("- Comparative extraction: `slower than speed of sound` captured")
    lines.append("- Synonym normalization: `tallest` ≡ `highest` via canonical mapping")
    lines.append("- Prepositional relatedness: `in france` vs `in ulm` correctly refutes")
    lines.append("- Relation synonyms: `become` → `be`, `locate` → `be`")
    lines.append("")
    lines.append("### What still remains limited:")
    lines.append("- Coreference: 'It is located...' uses pronoun, subject never matches claim entity")
    lines.append("- Comparative inference: evidence states absolute values, not comparisons")
    lines.append("- Passive ACL subject mismatch: `shakespeare|write|tragedy` ≠ `shakespeare|write|hamlet`")
    lines.append("- Small dataset: 10 claims is insufficient for robust evaluation")

    path = output_dir / "error_analysis.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Error analysis written to %s", path)


def _run_demo(claim: str, config, retriever, extractor, reasoner) -> None:
    """Run a single claim through both pipelines and print a rich explanation."""
    from pipeline.krr import KRRPipeline
    from baseline.pipeline import BaselinePipeline
    from baseline.llm import KeywordLLM

    print("\n" + "=" * 70)
    print(f"  DEMO MODE — Claim: {claim}")
    print("=" * 70)

    # KRR
    krr = KRRPipeline(retriever=retriever, extractor=extractor,
                      reasoner=reasoner, config=config)
    krr_result = krr.run(claim)

    # Baseline
    baseline = BaselinePipeline(retriever=retriever,
                                llm_backend=KeywordLLM(), config=config)
    bl_result = baseline.run(claim)

    print("\n--- BASELINE (Keyword) ---")
    print(f"  Verdict : {bl_result.verdict}")
    print(f"  Evidence: {bl_result.retrieved_evidence[0] if bl_result.retrieved_evidence else '(none)'}")

    print("\n--- KRR VERDICT ---")
    print(f"  Verdict        : {krr_result.verdict}")
    print(f"  Support count  : {krr_result.support_count}")
    print(f"  Refute count   : {krr_result.refute_count}")
    print(f"  Irrelevant     : {krr_result.irrelevant_count}")
    if krr_result.attribution:
        print("  Attribution    :")
        for t in krr_result.attribution:
            print(f"    {t.to_canonical_string()}")
    print("=" * 70 + "\n")


def main(argv: list[str] | None = None) -> int:
    """Entry point for the KRR Fact Verification CLI.

    Args:
        argv: Optional argument list for testing; defaults to sys.argv[1:].

    Returns:
        Exit code (0 on success, 1 on fatal error).
    """
    args = _parse_args(argv)

    # ------------------------------------------------------------------
    # 1. Load configuration
    # ------------------------------------------------------------------
    try:
        from config import Config, ConfigError, load_env_file

        load_env_file(args.env_file, override=False)
        config = Config.from_env(env_file=args.env_file)
        logger.info("Configuration loaded from %r.", args.env_file)
    except ConfigError as exc:
        logger.error("Configuration error: %s", exc)
        return 1
    except Exception as exc:  # noqa: BLE001
        logger.error("Unexpected error loading configuration: %s", exc)
        return 1

    # Override JSON output path if supplied on the command line.
    if args.output_json is not None:
        # Config is a frozen-ish dataclass but json_output_path is mutable.
        object.__setattr__(config, "json_output_path", args.output_json)

    # ------------------------------------------------------------------
    # 2. Load dataset
    # ------------------------------------------------------------------
    # Demo mode: verify a single claim and exit
    if args.claim:
        try:
            from retrieval.retriever import Retriever
            from knowledge.extractor import TripleExtractor
            from reasoning.reasoner import ReasoningModule
            from data.loader import DataLoader
            from dataclasses import replace as dc_replace

            # Build shared corpus from all available data
            corpus_sentences: list[str] = []
            seen: set[str] = set()
            for path in filter(None, [config.train_dataset_path, config.fever_dataset_path]):
                c = dc_replace(config, fever_dataset_path=path, max_records=None)
                for sent in DataLoader(c).load_corpus():
                    if sent not in seen:
                        seen.add(sent)
                        corpus_sentences.append(sent)

            retriever = Retriever(config)
            retriever.build_index(corpus_sentences)
            extractor = TripleExtractor(config)
            reasoner = ReasoningModule()
            _run_demo(args.claim, config, retriever, extractor, reasoner)
        except Exception as exc:
            logger.error("Demo mode failed: %s", exc)
            return 1
        return 0

    # ------------------------------------------------------------------
    # 3. Load dataset (batch mode)
    # ------------------------------------------------------------------
    try:
        from data.loader import DataLoader

        logger.info("Loading test dataset from %r.", config.fever_dataset_path)
        loader = DataLoader(config)
        records = loader.load()
        logger.info("Loaded %d test records.", len(records))
    except FileNotFoundError as exc:
        logger.error("Dataset file not found: %s", exc)
        return 1
    except Exception as exc:  # noqa: BLE001
        logger.error("Failed to load dataset: %s", exc)
        return 1

    if not records:
        logger.warning("No records loaded — nothing to evaluate.")
        return 0

    ground_truth = [record.label for record in records]
    claims = [record.claim for record in records]

    # ------------------------------------------------------------------
    # 3. Build / load retrieval index
    # ------------------------------------------------------------------
    try:
        from retrieval.retriever import Retriever

        retriever = Retriever(config)

        if config.index_path and Path(config.index_path).exists():
            logger.info("Loading pre-built index from %r.", config.index_path)
            retriever.load_index()
        else:
            # Build the retrieval corpus from ALL available evidence sentences.
            # In FEVER-style evaluation, the evidence corpus is a shared knowledge
            # base (Wikipedia) — it is NOT split between train and test.
            # Only the claims and labels are split.
            # We combine train + test evidence to simulate a shared corpus.
            corpus_sentences: list[str] = []
            seen_corpus: set[str] = set()

            def _add_corpus(path: str) -> None:
                from dataclasses import replace as dc_replace
                c = dc_replace(config, fever_dataset_path=path, max_records=None)
                for sent in DataLoader(c).load_corpus():
                    if sent not in seen_corpus:
                        seen_corpus.add(sent)
                        corpus_sentences.append(sent)

            # Always include training evidence (primary knowledge source)
            if config.train_dataset_path:
                _add_corpus(config.train_dataset_path)
                logger.info(
                    "Added training corpus from %r.", config.train_dataset_path
                )

            # Also include test evidence sentences (shared knowledge base —
            # no label leakage, only evidence text is used for retrieval)
            _add_corpus(config.fever_dataset_path)
            logger.info(
                "Added test corpus from %r (evidence only, no label leakage).",
                config.fever_dataset_path,
            )

            retriever.build_index(corpus_sentences)
            logger.info(
                "Retrieval index built over %d unique sentences.", len(corpus_sentences)
            )
    except Exception as exc:  # noqa: BLE001
        logger.error("Failed to initialize retriever: %s", exc)
        return 1

    # ------------------------------------------------------------------
    # 4. Initialize KRR-specific components (if needed)
    # ------------------------------------------------------------------
    krr_pipeline = None
    if args.pipeline in ("krr", "both"):
        try:
            from knowledge.extractor import TripleExtractor
            from reasoning.reasoner import ReasoningModule
            from pipeline.krr import KRRPipeline

            logger.info(
                "Initializing TripleExtractor (spaCy model=%s).", config.spacy_model
            )
            extractor = TripleExtractor(config)
            reasoner = ReasoningModule()
            krr_pipeline = KRRPipeline(
                retriever=retriever,
                extractor=extractor,
                reasoner=reasoner,
                config=config,
            )
            logger.info("KRR pipeline ready.")
        except Exception as exc:  # noqa: BLE001
            logger.error("Failed to initialize KRR pipeline: %s", exc)
            return 1

    # ------------------------------------------------------------------
    # 5. Initialize Baseline pipeline (if needed)
    # ------------------------------------------------------------------
    baseline_pipeline = None
    if args.pipeline in ("baseline", "both"):
        try:
            from baseline.pipeline import BaselinePipeline

            llm_backend = _build_llm_backend(config)
            baseline_pipeline = BaselinePipeline(
                retriever=retriever,
                llm_backend=llm_backend,
                config=config,
            )
            logger.info("Baseline RAG pipeline ready.")
        except Exception as exc:  # noqa: BLE001
            logger.error("Failed to initialize Baseline pipeline: %s", exc)
            return 1

    # ------------------------------------------------------------------
    # 6. Run pipeline(s) over all records
    # ------------------------------------------------------------------
    from models import BaselineResult, KRRResult

    krr_results: list[KRRResult] = []
    baseline_results: list[BaselineResult] = []

    total = len(claims)

    for i, (claim, record) in enumerate(zip(claims, records), 1):
        if i % max(1, total // 10) == 0 or i == total:
            logger.info("Processing claim %d / %d …", i, total)

        if krr_pipeline is not None:
            krr_result = krr_pipeline.run(claim)
            krr_results.append(krr_result)

        if baseline_pipeline is not None:
            baseline_result = baseline_pipeline.run(claim)
            baseline_results.append(baseline_result)

    # ------------------------------------------------------------------
    # 7. Evaluate and write report
    # ------------------------------------------------------------------
    try:
        from evaluation.evaluator import Evaluator

        evaluator = Evaluator()
        report = evaluator.evaluate(
            krr_results=krr_results if krr_pipeline is not None else None,
            baseline_results=baseline_results if baseline_pipeline is not None else None,
            ground_truth=ground_truth,
        )
        evaluator.save_report(report, path=config.eval_output_path)
        logger.info("Evaluation report written to %r.", config.eval_output_path)
    except Exception as exc:  # noqa: BLE001
        logger.error("Evaluation failed: %s", exc)
        return 1

    # ------------------------------------------------------------------
    # 8. Write error analysis report
    # ------------------------------------------------------------------
    try:
        _write_error_analysis(
            records=records,
            krr_results=krr_results if krr_pipeline is not None else None,
            baseline_results=baseline_results if baseline_pipeline is not None else None,
            output_dir=Path(config.eval_output_path).parent,
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("Error analysis generation failed (non-fatal): %s", exc)

    return 0


if __name__ == "__main__":
    sys.exit(main())
